version: "3.8"

services:
  financial-alert-api:
    depends_on:
      - mongo
    build:
      context: ../
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - 8081:8081
      - 5005:5005
    networks:
      - financial-alert
    environment:
      - FINANCIAL_ALERT_DB_URI=mongodb://root:password@mongo:27017/financial_alert
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  mongo:
    image: bitnami/mongodb
    restart: always
    ports:
      - 27017:27017
    networks:
      - financial-alert
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=financial_alert

networks:
  financial-alert:
    driver: bridge