version: "3.8"

services:
  financial-alert-api:
    depends_on:
      - mongodb
    build:
      context: ../
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - 8081:8081
      - 5005:5005
    networks:
      - financial-alert
    environment:
      - FINANCIAL_ALERT_DB_URI=mongodb://mongodb/financial_alert
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  mongodb:
    image: bitnami/mongodb:latest
    container_name: "mongodb"
    restart: always
    ports:
      - 27017:27017
    networks:
      - financial-alert
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

networks:
  financial-alert:
    driver: bridge