pipeline {
    agent any

    stages {
        stage ('Build Image') {
            steps {
                script {
                    dockerapp = docker.build('vitorcvargas/financial-info-api', '-f ./financial-info/Dockerfile ./financial-info')
                }
            }
        }
    }
}