name: financial-info
on:
  push:
    paths:
      - 'financial-info/**'
      - '.github/workflows/**'
    branches:
      - main

  pull_request:
    paths:
      - 'financial-info/**'
      - '.github/workflows/**'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Test - Unit and Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: mv -f financial-info/* .
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify

  sonar:
    name: Test - SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: mv -f financial-info/* .
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: SonarCloud Scan
        run: mvn -B clean verify -Pcoverage,sonar -Dsonar.projectKey=financial-info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}