spring:
  datasource:
    url: ${FINANCIAL_INFO_DB_URL}
    username: ${FINANCIAL_INFO_DB_USERNAME}
    password: ${FINANCIAL_INFO_DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html

